### ISSUE TITLE
I can`t get vimrc

### ISSUE THREAD

**Issue by 0x007004** [lefticus/vimconfig#1]
it is so cool , but i can`t get the file which is vimrc . Can you move it to  github?

**Comment by lefticus** [comment]
It's in there, you just have to follow the submodule links https://github.com/lefticus/vimconfig

https://github.com/lefticus/vimconfig/tree/master/submodules

But also I haven't updated the vim config in a very long time, I use neovim exclusively now https://github.com/lefticus/nvim-config

**Comment by 0x007004** [comment]
thank you.
